ARG IMAGE_NAME="ubuntu:latest"
FROM $IMAGE_NAME

ENV DEBIAN_FRONTEND noninteractive

# Install a couple dependencies + extra packages
RUN apt-get update --fix-missing -qq && apt-get install -qq \
    apt-utils \
    build-essential \
    curl \
    gcc \
    git \
    gpp \
    locales \
    libncurses5-dev \
    libreadline-dev \
    libssl-dev

# Set the locale
RUN echo "fr_FR.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen fr_FR.UTF-8 && \
    dpkg-reconfigure locales && \
    /usr/sbin/update-locale LANG=fr_FR.UTF-8
ENV LC_ALL fr_FR.UTF-8  

# From Zonemaster Engine installation instruction 
RUN apt-get install --no-install-recommends -qq gettext libgettextpo-dev autoconf automake build-essential cpanminus libclone-perl libfile-sharedir-perl libfile-slurp-perl libidn11-dev libintl-perl libio-socket-inet6-perl libjson-pp-perl liblist-moreutils-perl liblocale-msgfmt-perl libmail-rfc822-address-perl libmodule-find-perl libnet-ip-perl libpod-coverage-perl libreadonly-perl libreadonly-xs-perl libssl-dev libtest-differences-perl libtest-exception-perl libtest-fatal-perl libtest-pod-perl libtext-csv-perl libtool m4

# Zonemaster LDNS needs a newer version of Module::Install
RUN cpan install Module::Install Module::Install::XSUtil && \
    # Zonemaster Backend transitively needs a newer version of Devel::CheckLib
    cpan install Devel::CheckLib && \
    # Moose installed from OS packages depend on a newer version of Devel::OverloadInfo
    cpan install Devel::OverloadInfo Moose && \ 
    # IO::Socket::INET6 can't find Socket6 unless it's installed from CPAN
    cpan install Socket6

    # Install Zonemaster LDNS
RUN git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-ldns.git && \
    ( cd zonemaster-ldns && cpanm --verbose --notest --configure-args="--no-ed25519" . ) && rm -rf zonemaster-ldns

    # Install Zonemaster Engine
RUN git clone --depth=1 --branch=develop https://github.com/zonemaster/zonemaster-engine.git && \
    ( cd zonemaster-ldns && PERL_CPANM_OPT="--configure-args=--no-ed25519" cpan-install . ) && rm -rf zonemaster-ldns

